"""Initial migration

Revision ID: b581b8de0c7e
Revises:
Create Date: 2023-05-28 12:42:48.982267

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Float, Integer, String, column, table

# revision identifiers, used by Alembic.
revision = 'b581b8de0c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50)),
                    sa.Column('vocation', sa.String(length=10)),
                    sa.Column('x_max', sa.Float()),
                    sa.Column('y_max', sa.Integer()),
                    sa.Column('x_min', sa.Float()),
                    sa.Column('y_min', sa.Integer()),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    # Populate the table with starter data
    all_spells = [
        {
            'name': 'Avalanche',
            'vocation': 'druid',
            'x_max': 2.85,
            'y_max': 16,
            'x_min': 1.2,
            'y_min': 7
        },
        {
            'name': 'Energy Strike',
            'vocation': 'druid',
            'x_max': 2.203,
            'y_max': 14,
            'x_min': 1.403,
            'y_min': 8
        },
        {
            'name': 'Eternal Winter',
            'vocation': 'druid',
            'x_max': 11,
            'y_max': 50,
            'x_min': 5.5,
            'y_min': 25
        },
        {
            'name': 'Explosion',
            'vocation': 'druid',
            'x_max': 3.2,
            'y_max': 19,
            'x_min': 1.6,
            'y_min': 9
        },
        {
            'name': 'Fireball',
            'vocation': 'druid',
            'x_max': 3,
            'y_max': 17,
            'x_min': 1.81,
            'y_min': 12
        },
        {
            'name': 'Heal Friend',
            'vocation': 'druid',
            'x_max': 14.4,
            'y_max': 90,
            'x_min': 6.3,
            'y_min': 45
        },
        {
            'name': 'Heavy Magic Missile',
            'vocation': 'druid',
            'x_max': 1.59,
            'y_max': 10,
            'x_min': 0.81,
            'y_min': 5
        },
        {
            'name': 'Ice Wave',
            'vocation': 'druid',
            'x_max': 2,
            'y_max': 12,
            'x_min': 0.81,
            'y_min': 5
        },
        {
            'name': 'Intense Healing',
            'vocation': 'druid',
            'x_max': 6,
            'y_max': 37,
            'x_min': 3.6,
            'y_min': 22
        },
        {
            'name': 'Light Healing',
            'vocation': 'druid',
            'x_max': 1.8,
            'y_max': 11,
            'x_min': 1.4,
            'y_min': 8
        },
        {
            'name': 'Light Magic Missile',
            'vocation': 'druid',
            'x_max': 0.81,
            'y_max': 4,
            'x_min': 0.4,
            'y_min': 3
        },
        {
            'name': 'Mass Healing',
            'vocation': 'druid',
            'x_max': 9.6,
            'y_max': 125,
            'x_min': 4.6,
            'y_min': 100
        },
        {
            'name': 'Physical Strike',
            'vocation': 'druid',
            'x_max': 2.203,
            'y_max': 14,
            'x_min': 1.403,
            'y_min': 8
        },
        {
            'name': 'Stalagmite',
            'vocation': 'druid',
            'x_max': 1.59,
            'y_max': 10,
            'x_min': 0.81,
            'y_min': 5
        },
        {
            'name': 'Stone Shower',
            'vocation': 'druid',
            'x_max': 2.6,
            'y_max': 16,
            'x_min': 1,
            'y_min': 6
        },
        {
            'name': 'Strong Ice Strike',
            'vocation': 'druid',
            'x_max': 4.4,
            'y_max': 28,
            'x_min': 2.8,
            'y_min': 16
        },
        {
            'name': 'Strong Ice Wave',
            'vocation': 'druid',
            'x_max': 7.6,
            'y_max': 48,
            'x_min': 4.5,
            'y_min': 20
        },
        {
            'name': 'Sudden Death',
            'vocation': 'druid',
            'x_max': 7.4,
            'y_max': 48,
            'x_min': 4.3,
            'y_min': 32
        },
        {
            'name': 'Terra Wave',
            'vocation': 'druid',
            'x_max': 6.75,
            'y_max': 30,
            'x_min': 3.25,
            'y_min': 5
        },
        {
            'name': 'Ultimate Healing',
            'vocation': 'druid',
            'x_max': 12.9,
            'y_max': 90,
            'x_min': 6.8,
            'y_min': 42
        },
        {
            'name': 'Ultimate Ice Strike',
            'vocation': 'druid',
            'x_max': 7.3,
            'y_max': 55,
            'x_min': 4.5,
            'y_min': 35
        },
        {
            'name': 'Wrath of Nature',
            'vocation': 'druid',
            'x_max': 9,
            'y_max': 40,
            'x_min': 3,
            'y_min': 32
        }
    ]

    spells_table = table('spells',
                         column('name', String(50)),
                         column('vocation', String(10)),
                         column('x_max', Float),
                         column('y_max', Integer),
                         column('x_min', Float),
                         column('y_min', Integer)
                         )
    op.bulk_insert(spells_table, all_spells)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spells')
    # ### end Alembic commands ###
